# Generated by Django 4.2.2 on 2023-07-01 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles_db_app', '0002_remove_gradingsystem_condition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], db_index=True, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('collectible_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests', to='collectibles_db_app.collectibleitem', verbose_name='collectible_items')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_request', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_request', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'friendrequest',
                'verbose_name_plural': 'friendrequests',
            },
        ),
    ]
