# Generated by Django 4.2.2 on 2023-06-28 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=70, verbose_name='value')),
            ],
            options={
                'verbose_name': 'condition',
                'verbose_name_plural': 'conditions',
            },
        ),
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=2000, verbose_name='description')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_systems', to='collectibles_db_app.condition', verbose_name='condition')),
            ],
            options={
                'verbose_name': 'grading_system',
                'verbose_name_plural': 'grading_systems',
            },
        ),
        migrations.CreateModel(
            name='CollectibleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('currency', models.CharField(max_length=100, verbose_name='currency')),
                ('release_year', models.IntegerField(verbose_name='release_year')),
                ('circulation', models.IntegerField(verbose_name='circulation')),
                ('item_type', models.PositiveSmallIntegerField(choices=[(1, 'Circulation Coins'), (2, 'Banknotes'), (3, 'Commemorative Coins'), (4, 'Circulating Commemoratives'), (5, 'Collector Coins'), (6, 'Bullion Coins'), (7, 'Medals'), (8, 'Other')], db_index=True, verbose_name='item_type')),
                ('denomination', models.FloatField(verbose_name='denomination')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('description', models.CharField(max_length=3000, verbose_name='description')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='register_date')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='update date')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectible_items', to='collectibles_db_app.gradingsystem', verbose_name='condition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectible_items', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'collectible_item',
                'verbose_name_plural': 'collectible_items',
            },
        ),
    ]
