# Generated by Django 4.2.2 on 2023-07-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles_db_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='circulation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='circulation'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='release_year',
            field=models.PositiveIntegerField(verbose_name='release_year'),
        ),
    ]
