# Generated by Django 4.2.2 on 2023-07-06 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collectibles_db_app', '0002_remove_gradingsystem_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='value')),
            ],
            options={
                'verbose_name': 'value',
                'verbose_name_plural': 'values',
            },
        ),
        migrations.AddField(
            model_name='collectibleitem',
            name='obverse_side',
            field=models.ImageField(blank=True, null=True, upload_to='collectibles/obverse_side', verbose_name='obverse_side'),
        ),
        migrations.AddField(
            model_name='collectibleitem',
            name='reverse_side',
            field=models.ImageField(blank=True, null=True, upload_to='collectibles/reverse_side', verbose_name='reverse_side'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='circulation',
            field=models.IntegerField(blank=True, null=True, verbose_name='circulation'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='denomination',
            field=models.FloatField(blank=True, null=True, verbose_name='denomination'),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='description'),
        ),
        migrations.CreateModel(
            name='GradationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradation_systems', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradation_systems', to='collectibles_db_app.value', verbose_name='value')),
            ],
            options={
                'verbose_name': 'gradation_system',
                'verbose_name_plural': 'gradation_systems',
            },
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectible_items', to='collectibles_db_app.gradationsystem', verbose_name='condition'),
        ),
    ]
